name: deploy

on:
    push:
        branches:
        - master


jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    
    env:
      OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Load secrets from 1Password
      uses: 1password/load-secrets-action@v2
      with:
        # Export loaded secrets as environment variables
        export-env: true
      env:
        OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
        GCP_SERVICE_ACCOUNT_KEY: op://bee-ci/Google Cloud/service account key
        GCP_PROJECT_ID: op://bee-ci/Google Cloud/project id

    - name: Authenticate to gcloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ env.GCP_SERVICE_ACCOUNT_KEY }}
        
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        version: latest
        project_id: ${{ env.GCP_PROJECT_ID }}

    - name: Deploy to GCP
      run: ./build-container
